apiVersion: v1
kind: Service
metadata:
  name: users-ms
spec:
  type: NodePort
  selector:
    app: {{ template "fullname" . }}-user-management-ms
  ports:
    - port: {{ .Values.services.userManagmentMs.port }}
      targetPort: {{ .Values.services.userManagmentMs.port }}