apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-fe-website
spec:
  replicas: {{ .Values.services.feWebsite.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-fe-website
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-fe-website
    spec:
      nodeSelector:
      #        environment: {{ .Release.Name }}
      containers:
        - name: {{ template "fullname" . }}-fe-website
          image: {{ .Values.services.feWebsite.image }}:{{ .Values.services.feWebsite.tag }}
          resources:
            limits:
              memory: {{ .Values.services.feWebsite.limits.memory }}
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.services.feWebsite.port }}
          env:
            - name: DB_HOST
              value: {{ template "fullname" . }}-postgress