apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-mysql
spec:
  replicas: {{ .Values.services.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-mysql
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-mysql
    spec:
      nodeSelector:
      #        environment: {{ .Release.Name }}
      containers:
        - name: {{ template "fullname" . }}-mysql
          image: {{ .Values.services.mysql.image }}:{{ .Values.services.mysql.tag }}
          resources:
            limits:
              memory: {{ .Values.services.mysql.limits.memory }}
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - containerPort: {{ .Values.services.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "ayaz1997"
      volumes:
          - name: mysql-data
            persistentVolumeClaim:
              claimName: {{ template "fullname" . }}-mysql
