version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - myvolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ayaz1997
    ports:
      - 3306:3306

volumes:
  myvolume: