services:
  userManagmentMs:
    replicaCount: 2
    port: '8080'
    image:  ayaznacafli/prime-user-managment-ms
    tag: '0.1.ec5ec7e'
    limits:
      memory: "400M"
  mysql:
    replicaCount: 2
    port: '3306'
    image:  mysql
    tag: 'latest'
    limits:
      memory: "400M"